'''
Author        : fineemb
Github        : https://github.com/fineemb
Description   : 
Date          : 2020-10-05 14:48:08
LastEditors   : fineemb
LastEditTime  : 2020-10-10 19:14:18
'''


"""Const file for Xiaomi Cloud."""
NAME = "Lynk&Co"
CONF_WAKE_ON_START = "enable_wake_on_start"
DOMAIN = "lynkco"
COORDINATOR = "coordinator"
DATA_LISTENER = "listener"
UNDO_UPDATE_LISTENER = "undo_update_listener"
DEFAULT_SCAN_INTERVAL = 660
DEFAULT_WAKE_ON_START = False
MIN_SCAN_INTERVAL = 60
SIGNAL_STATE_UPDATED = f"{DOMAIN}.updated"
LYNKCO_COMPONENT = ['device_tracker','sensor','binary_sensor']
ATTR_ICON = "icon"
ATTR_LABEL = "label"
ATTR_UNIT_IMPERIAL = "Imperial"
ATTR_UNIT_METRIC = "Metric"
ATTR_FRIENDLY_NAME = "friendly_name"
ATTR_VEHICLE_STATUS = 'vehicle_status'
ATTR_ADD_VEHICLE_STATUS = 'additionalVehicleStatus'

from homeassistant.const import (
    ATTR_DEVICE_CLASS,
    DEVICE_CLASS_TEMPERATURE,
    LENGTH_FEET,
    LENGTH_INCHES,
    LENGTH_METERS,
    SPEED_KILOMETERS_PER_HOUR,
    SPEED_MILES_PER_HOUR,
    LENGTH_MILES,
    LENGTH_KILOMETERS,
    LENGTH_INCHES,
    TEMP_CELSIUS,
    TEMP_FAHRENHEIT,
    VOLUME_LITERS,
    TIME_HOURS,
    TIME_DAYS,
    DEGREE,
    UV_INDEX,
    VOLUME_CUBIC_METERS,
)

OPTIONAL_SENSORS = (

    "interiorTemp",
    "ventilateStatus",
    "preClimateActive"
)
BINARY_SENSOR_TYPES = {
    "seatBeltStatusDriverRear": {
        ATTR_DEVICE_CLASS: "lock",
        ATTR_ICON: "mdi:seatbelt",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "drivingSafetyStatus",
        ATTR_LABEL: "Seat belt status driver rear",
        ATTR_FRIENDLY_NAME: '左后安全带',
    },
    "seatBeltStatusDriver": {
        ATTR_DEVICE_CLASS: "lock",
        ATTR_ICON: "mdi:seatbelt",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "drivingSafetyStatus",
        ATTR_LABEL: "Seat belt status driver",
        ATTR_FRIENDLY_NAME: '左前安全带',
    },
    "seatBeltStatusPassenger": {
        ATTR_DEVICE_CLASS: "lock",
        ATTR_ICON: "mdi:seatbelt",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "drivingSafetyStatus",
        ATTR_LABEL: "Seat belt status passenger",
        ATTR_FRIENDLY_NAME: '右前安全带',
    },
    "seatBeltStatusPassengerRear": {
        ATTR_DEVICE_CLASS: "lock",
        ATTR_ICON: "mdi:seatbelt",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "drivingSafetyStatus",
        ATTR_LABEL: "Seat belt status passenger rear",
        ATTR_FRIENDLY_NAME: '右后安全带',
    },
    "doorOpenStatusDriverRear": {
        ATTR_DEVICE_CLASS: "door",
        ATTR_ICON: "mdi:car-door",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "drivingSafetyStatus",
        ATTR_LABEL: "Door open status driver rear",
        ATTR_FRIENDLY_NAME: '左后门状态',
    },
    "doorOpenStatusDriver": {
        ATTR_DEVICE_CLASS: "door",
        ATTR_ICON: "mdi:car-door",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "drivingSafetyStatus",
        ATTR_LABEL: "Door open status driver",
        ATTR_FRIENDLY_NAME: '左前门状态',
    },
    "doorOpenStatusPassenger": {
        ATTR_DEVICE_CLASS: "door",
        ATTR_ICON: "mdi:car-door",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "drivingSafetyStatus",
        ATTR_LABEL: "Door open status passenger",
        ATTR_FRIENDLY_NAME: '右前门状态',
    },
    "doorOpenStatusPassengerRear": {
        ATTR_DEVICE_CLASS: "door",
        ATTR_ICON: "mdi:car-door",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "drivingSafetyStatus",
        ATTR_LABEL: "Door open status passenger rear",
        ATTR_FRIENDLY_NAME: '右后门状态',
    },
    "tyrePreWarningDriver": {
        ATTR_DEVICE_CLASS: "safety",
        ATTR_ICON: "mdi:car-tire-alert",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "maintenanceStatus",
        ATTR_LABEL: "Tyre pre warning driver",
        ATTR_FRIENDLY_NAME: '左前轮胎预警',
    },
    "tyrePreWarningPassenger": {
        ATTR_DEVICE_CLASS: "safety",
        ATTR_ICON: "mdi:car-tire-alert",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "maintenanceStatus",
        ATTR_LABEL: "Tyre pre warning passenger",
        ATTR_FRIENDLY_NAME: '右前轮胎预警',
    },
    "tyrePreWarningDriverRear": {
        ATTR_DEVICE_CLASS: "safety",
        ATTR_ICON: "mdi:car-tire-alert",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "maintenanceStatus",
        ATTR_LABEL: "Tyre pre warning driver rear",
        ATTR_FRIENDLY_NAME: '左后轮胎预警',
    },
    "tyrePreWarningPassengerRear": {
        ATTR_DEVICE_CLASS: "safety",
        ATTR_ICON: "mdi:car-tire-alert",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "maintenanceStatus",
        ATTR_LABEL: "Tyre pre warning passenger rear",
        ATTR_FRIENDLY_NAME: '右后轮胎预警',
    },
    "doorLockStatusDriverRear": {
        ATTR_DEVICE_CLASS: "lock",
        ATTR_ICON: "mdi:car-door-lock",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "drivingSafetyStatus",
        ATTR_LABEL: "Door lock status driver rear",
        ATTR_FRIENDLY_NAME: '左后门锁',
    },
    "doorLockStatusDriver": {
        ATTR_DEVICE_CLASS: "lock",
        ATTR_ICON: "mdi:car-door-lock",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "drivingSafetyStatus",
        ATTR_LABEL: "Door lock status driver",
        ATTR_FRIENDLY_NAME: '左前门锁',
    },
    "doorLockStatusPassenger": {
        ATTR_DEVICE_CLASS: "lock",
        ATTR_ICON: "mdi:car-door-lock",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "drivingSafetyStatus",
        ATTR_LABEL: "Door lock status passenger",
        ATTR_FRIENDLY_NAME: '右前门锁',
    },
    "doorLockStatusPassengerRear": {
        ATTR_DEVICE_CLASS: "lock",
        ATTR_ICON: "mdi:car-door-lock",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "drivingSafetyStatus",
        ATTR_LABEL: "Door lock status passenger rear",
        ATTR_FRIENDLY_NAME: '右后门锁',
    },
    "trunkLockStatus": {
        ATTR_DEVICE_CLASS: "lock",
        ATTR_ICON: "mdi:lock-reset",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "drivingSafetyStatus",
        ATTR_LABEL: "Trunk lock status",
        ATTR_FRIENDLY_NAME: '行李箱锁状态',
    },
    "trunkOpenStatus": {
        ATTR_DEVICE_CLASS: "door",
        ATTR_ICON: "mdi:car-back",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "drivingSafetyStatus",
        ATTR_LABEL: "Trunk open status",
        ATTR_FRIENDLY_NAME: '行李箱打开状态',
    },
    "engineHoodOpenStatus": {
        ATTR_DEVICE_CLASS: "door",
        ATTR_ICON: "mdi:car-windshield",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "drivingSafetyStatus",
        ATTR_LABEL: "Engine hood open status",
        ATTR_FRIENDLY_NAME: '引擎盖',
    },
}
SENSOR_TYPES = {
    "keyStatus": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:car-key",
        ATTR_VEHICLE_STATUS: "basicVehicleStatus",
        ATTR_LABEL: "Key status",
        ATTR_FRIENDLY_NAME: '钥匙状态',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "engineStatus": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:engine",
        ATTR_VEHICLE_STATUS: "basicVehicleStatus",
        ATTR_LABEL: "Engine status",
        ATTR_FRIENDLY_NAME: '引擎状态',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "speed": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:speedometer-slow",
        ATTR_VEHICLE_STATUS: "basicVehicleStatus",
        ATTR_LABEL: "Speed",
        ATTR_FRIENDLY_NAME: '速度',
        ATTR_UNIT_METRIC: SPEED_MILES_PER_HOUR,
        ATTR_UNIT_IMPERIAL: SPEED_KILOMETERS_PER_HOUR,
    },
    "direction": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:directions",
        ATTR_VEHICLE_STATUS: "basicVehicleStatus",
        ATTR_LABEL: "Direction",
        ATTR_FRIENDLY_NAME: '方向',
        ATTR_UNIT_METRIC: DEGREE,
        ATTR_UNIT_IMPERIAL: DEGREE,
    },
    "distanceToEmpty": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:map-marker-distance",
        ATTR_VEHICLE_STATUS: "basicVehicleStatus",
        ATTR_LABEL: "Distance To Empty",
        ATTR_FRIENDLY_NAME: '剩余公里数',
        ATTR_UNIT_METRIC: LENGTH_KILOMETERS,
        ATTR_UNIT_IMPERIAL: LENGTH_KILOMETERS,
    },
    "ecuWarningMessages": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:alert-octagon",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "ecuWarningMessages",
        ATTR_LABEL: "ECU Warning Messages",
        ATTR_FRIENDLY_NAME: 'ECU警告',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "exteriorTemp": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:thermometer",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "climateStatus",
        ATTR_LABEL: "Exterior temp",
        ATTR_FRIENDLY_NAME: '车外温度',
        ATTR_UNIT_METRIC: TEMP_CELSIUS,
        ATTR_UNIT_IMPERIAL: TEMP_CELSIUS,
    },
    "interiorTemp": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:home-thermometer",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "climateStatus",
        ATTR_LABEL: "Interior temp",
        ATTR_FRIENDLY_NAME: '车内温度',
        ATTR_UNIT_METRIC: TEMP_CELSIUS,
        ATTR_UNIT_IMPERIAL: TEMP_CELSIUS,
    },
    "winStatusDriverRear": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:window-shutter",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "climateStatus",
        ATTR_LABEL: "Win status driver rear",
        ATTR_FRIENDLY_NAME: '左后车窗',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "winStatusDriver": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:window-shutter",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "climateStatus",
        ATTR_LABEL: "Win status driver",
        ATTR_FRIENDLY_NAME: '左前车窗',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "winStatusPassengerRear": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:window-shutter",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "climateStatus",
        ATTR_LABEL: "Win status passenger rear",
        ATTR_FRIENDLY_NAME: '右后车窗',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "winStatusPassenger": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:window-shutter",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "climateStatus",
        ATTR_LABEL: "Win status passenger",
        ATTR_FRIENDLY_NAME: '右前车窗',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "sunroofOpenStatus": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:window-closed",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "climateStatus",
        ATTR_LABEL: "Sunroof open status",
        ATTR_FRIENDLY_NAME: '天窗',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "ventilateStatus": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:fan",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "climateStatus",
        ATTR_LABEL: "Ventilate status",
        ATTR_FRIENDLY_NAME: '通风',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "preClimateActive": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:air-conditioner",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "climateStatus",
        ATTR_LABEL: "Pre climate active",
        ATTR_FRIENDLY_NAME: '锁车前空调激活',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "cruiseControlStatus": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:car-cruise-control",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "drivingBehaviourStatus",
        ATTR_LABEL: "Cruise control status",
        ATTR_FRIENDLY_NAME: '巡航控制状态',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "brakePedalDepressed": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:car-brake-alert",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "drivingBehaviourStatus",
        ATTR_LABEL: "Brake pedal depressed",
        ATTR_FRIENDLY_NAME: '刹车',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "transimissionGearPostion": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:cog",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "drivingBehaviourStatus",
        ATTR_LABEL: "Transimission gear postion",
        ATTR_FRIENDLY_NAME: '变速箱齿轮位置',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "engineSpeed": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:speedometer",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "drivingBehaviourStatus",
        ATTR_LABEL: "Engine speed",
        ATTR_FRIENDLY_NAME: '引擎速度',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "engineHrsToService": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:engine-outline",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "maintenanceStatus",
        ATTR_LABEL: "Engine Hrs to service",
        ATTR_FRIENDLY_NAME: '引擎维护',
        ATTR_UNIT_METRIC: TIME_DAYS,
        ATTR_UNIT_IMPERIAL: TIME_DAYS,
    },
    "daysToService": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:account-cog",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "maintenanceStatus",
        ATTR_LABEL: "Days to service",
        ATTR_FRIENDLY_NAME: '保养(时间)',
        ATTR_UNIT_METRIC: TIME_DAYS,
        ATTR_UNIT_IMPERIAL: TIME_DAYS,
    },
    "odometer": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:av-timer",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "maintenanceStatus",
        ATTR_LABEL: "Odometer",
        ATTR_FRIENDLY_NAME: '总里程',
        ATTR_UNIT_METRIC: LENGTH_KILOMETERS,
        ATTR_UNIT_IMPERIAL: LENGTH_KILOMETERS,
    },
    "brakeFluidLevelStatus": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:hydraulic-oil-level",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "maintenanceStatus",
        ATTR_LABEL: "Brake fluid level status",
        ATTR_FRIENDLY_NAME: '制动液',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "tyreStatusDriver": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:movie-roll",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "maintenanceStatus",
        ATTR_LABEL: "Tyre status driver",
        ATTR_FRIENDLY_NAME: '左前轮胎压',
        ATTR_UNIT_METRIC: "kpa",
        ATTR_UNIT_IMPERIAL: "kpa",
    },
    "tyreStatusPassenger": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:movie-roll",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "maintenanceStatus",
        ATTR_LABEL: "Tyre status passenger",
        ATTR_FRIENDLY_NAME: '右前轮胎压',
        ATTR_UNIT_METRIC: "kpa",
        ATTR_UNIT_IMPERIAL: "kpa",
    },
    "tyreStatusDriverRear": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:movie-roll",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "maintenanceStatus",
        ATTR_LABEL: "Tyre status driver rear",
        ATTR_FRIENDLY_NAME: '左后轮胎压',
        ATTR_UNIT_METRIC: "kpa",
        ATTR_UNIT_IMPERIAL: "kpa",
    },
    "tyreStatusPassengerRear": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:movie-roll",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "maintenanceStatus",
        ATTR_LABEL: "Tyre status passenger rear",
        ATTR_FRIENDLY_NAME: '右后轮胎压',
        ATTR_UNIT_METRIC: "kpa",
        ATTR_UNIT_IMPERIAL: "kpa",
    },
    "distanceToService": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:account-cog",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "maintenanceStatus",
        ATTR_LABEL: "Distance to service",
        ATTR_FRIENDLY_NAME: '保养(公里)',
        ATTR_UNIT_METRIC: LENGTH_KILOMETERS,
        ATTR_UNIT_IMPERIAL: LENGTH_KILOMETERS,
    },
    "serviceWarningTrigger": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:account-alert",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "maintenanceStatus",
        ATTR_LABEL: "Service warning trigger",
        ATTR_FRIENDLY_NAME: '保养警告触发',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "serviceWarningStatus": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:account-alert",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "maintenanceStatus",
        ATTR_LABEL: "Service warning status",
        ATTR_FRIENDLY_NAME: '保养警告状态',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "washerFluidLevelStatus": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:dishwasher",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "maintenanceStatus",
        ATTR_LABEL: "Washer fluid level status",
        ATTR_FRIENDLY_NAME: '洗涤液',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "mainBatteryStatus": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:car-battery",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "maintenanceStatus",
        ATTR_LABEL: "Main battery status",
        ATTR_FRIENDLY_NAME: '主电池',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "fuelLevelStatus": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:fuel",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "runningStatus",
        ATTR_LABEL: "Fuel level status",
        ATTR_FRIENDLY_NAME: '剩余燃油状态',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "aveFuelConsumptionInLatestDrivingCycle": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:fuel",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "runningStatus",
        ATTR_LABEL: "Ave fuel consumption in latest driving cycle",
        ATTR_FRIENDLY_NAME: '周期油耗',
        ATTR_UNIT_METRIC: VOLUME_LITERS,
        ATTR_UNIT_IMPERIAL: VOLUME_LITERS,
    },
    "engineOilPressureWarning": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:oil-lamp",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "runningStatus",
        ATTR_LABEL: "Engine oil pressure warning",
        ATTR_FRIENDLY_NAME: '机油预警',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "bulbStatus": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:lightbulb",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "runningStatus",
        ATTR_LABEL: "Bulb status",
        ATTR_FRIENDLY_NAME: '灯泡状态',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "engineCoolantTemperature": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:coolant-temperature",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "runningStatus",
        ATTR_LABEL: "Engine coolant Temperature",
        ATTR_FRIENDLY_NAME: '冷却液温度',
        ATTR_UNIT_METRIC: TEMP_CELSIUS,
        ATTR_UNIT_IMPERIAL: TEMP_CELSIUS,
    },
    "engineCoolantLevelStatus": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:car-coolant-level",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "runningStatus",
        ATTR_LABEL: "Engine coolant level status",
        ATTR_FRIENDLY_NAME: '冷却液状态',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "engineOilLevelStatus": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:oil-level",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "runningStatus",
        ATTR_LABEL: "Engine oil level status",
        ATTR_FRIENDLY_NAME: '机油状态',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "tripMeter1": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:road-variant",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "runningStatus",
        ATTR_LABEL: "Trip meter1",
        ATTR_FRIENDLY_NAME: '行程表1',
        ATTR_UNIT_METRIC: LENGTH_KILOMETERS,
        ATTR_UNIT_IMPERIAL: LENGTH_KILOMETERS,
    },
    "tripMeter2": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:road-variant",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "runningStatus",
        ATTR_LABEL: "Trip meter2",
        ATTR_FRIENDLY_NAME: '行程表2',
        ATTR_UNIT_METRIC: LENGTH_KILOMETERS,
        ATTR_UNIT_IMPERIAL: LENGTH_KILOMETERS,
    },
    "aveFuelConsumption": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:fuel",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "runningStatus",
        ATTR_LABEL: "Ave fuel consumption",
        ATTR_FRIENDLY_NAME: '平均油耗',
        ATTR_UNIT_METRIC: VOLUME_LITERS,
        ATTR_UNIT_IMPERIAL: VOLUME_LITERS,
    },
    "avgSpeed": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:speedometer-medium",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "runningStatus",
        ATTR_LABEL: "Avg speed",
        ATTR_FRIENDLY_NAME: '平均速度',
        ATTR_UNIT_METRIC: SPEED_MILES_PER_HOUR,
        ATTR_UNIT_IMPERIAL: SPEED_KILOMETERS_PER_HOUR,
    },
    "srsStatus": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:airbag",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "drivingSafetyStatus",
        ATTR_LABEL: "SRS status",
        ATTR_FRIENDLY_NAME: '气囊状态',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "centralLockingStatus": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:shield-lock",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "drivingSafetyStatus",
        ATTR_LABEL: "Central locking status",
        ATTR_FRIENDLY_NAME: '中央锁状态',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "handBrakeStatus": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:car-brake-hold",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "drivingSafetyStatus",
        ATTR_LABEL: "Hand brake status",
        ATTR_FRIENDLY_NAME: '手刹状态',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
    "vehicleAlarm": {
        ATTR_DEVICE_CLASS: "lynkco_car",
        ATTR_ICON: "mdi:car-connected",
        ATTR_VEHICLE_STATUS: "additionalVehicleStatus",
        ATTR_ADD_VEHICLE_STATUS: "drivingSafetyStatus",
        ATTR_LABEL: "Vehicle alarm",
        ATTR_FRIENDLY_NAME: '车辆警报',
        ATTR_UNIT_METRIC: None,
        ATTR_UNIT_IMPERIAL: None,
    },
}